services:
  node1:
    hostname: node1
    image: adoptopenjdk
    volumes:
    - ".:/opt/project"
    ports:
      - "9091:9090"
    networks:
      default-net:
        ipv4_address: 192.168.1.101
    working_dir: /opt/project
    command: java -cp /opt/project/target/itch-1.0.2.jar com.sorintlab.itch.Itch

  node2:
    hostname: node2
    image: adoptopenjdk
    volumes:
      - ".:/opt/project"
    ports:
      - "9092:9090"
    networks:
      default-net:
        ipv4_address: 192.168.1.102
    working_dir: /opt/project
    command: java -cp /opt/project/target/itch-1.0.2.jar com.sorintlab.itch.Itch

  node3:
    hostname: node3
    image: adoptopenjdk
    volumes:
      - ".:/opt/project"
    ports:
      - "9093:9090"
    networks:
      default-net:
        ipv4_address: 192.168.1.103
    working_dir: /opt/project
    command: java -cp /opt/project/target/itch-1.0.2.jar com.sorintlab.itch.Itch

networks:
  default-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
